src/__tests__/node.js, src/selectors/node.js
The DOM4 [replaceWith](https://dom.spec.whatwg.org/#dom-childnode-replacewithnodes) method accepts multiple elements. Feature parity would be helpful in **postcss** and **postcss-selector-parser**.
- Updates replaceWith method
- Updates replaceWith test
Examples:
```js
/* without replaceWith support for multiple nodes */
let id = parser.id({ value: 'id' });
let className = parser.className({ value: 'class' });
if (node.parent) {
node.parent.insertBefore(node, id);
node.parent.insertBefore(node, className);
node.removeSelf();
}
```
```js
/* with replaceWith support for multiple nodes */
let id = parser.id({ value: 'id' });
let className = parser.className({ value: 'class' });
node.replaceWith(id, className);
```
=> Support multiple nodes on replaceWith

src/__tests__/exceptions.js, src/parser.js
Hello, 
When parsing an invalid pseudo class I would get an exception show below.  I have made a change to throw a more friendly and expected error message 'Expected pseudo-class or pseudo-element'.  I looked at updating your test helper to allow to check for a proper exception message but didn't quite figure it out so currently the tests are hiding the issue by not asserting on the type of error.
```
:\inetpub\wwwroot\git\postcss-selector-parser\dist\parser.js:250
if (this.currToken[0] === 'word') {
^
TypeError: Cannot read property '0' of undefined
at Parser.pseudo (C:\inetpub\wwwroot\git\postcss-selector-parser\dist\parser.js:250:31)
at Parser.parse (C:\inetpub\wwwroot\git\postcss-selector-parser\dist\parser.js:372:26)
at Parser.loop …
```
=> fix error when parsing invalid pseudo class

src/__tests__/sourceIndex.js, src/parser.js, src/selectors/node.js, src/tokenize.js
This one is more intrusive then the others. Definitely curious if you think there's a better way.
What I did was add another data point to each token, representing its sourceIndex. For both token that only have line/column and those that have start and end line/columns, I tacked it onto the end of the token array, so it wouldn't break any existing stuff.
With that info in the token, complex multiline `sourceIndex`es kind of took care of themselves. I wrote a number of tests to add some confidence that it's working as expected.
What do you think?
If you accept this one, can you think of any other source line/column/sourceIndex work that needs to be done?
=> Add index to token for accurate sourceIndex

package.json
npm v3 tries to dedupe the dependencies by default, and keeping dependencies up-to-date helps better deduplication.
=> Update flatten from v0.0.1 to v1.x

API.md, CHANGELOG.md, src/__tests__/attributes.js, src/parser.js
Closes #50.
Does this look like what you were imagining, @ben-eb?
If this is accepted, the only other issue holding up 2.0 is a simple find-replace, right?
=> Adds quoted and raw.unquoted properties to attribute nodes

src/index.js, src/parser.js, src/selectors/attribute.js, src/selectors/className.js, src/selectors/combinator.js, src/selectors/comment.js, src/selectors/container.js, src/selectors/id.js, src/selectors/nesting.js, src/selectors/pseudo.js, src/selectors/root.js, src/selectors/selector.js, src/selectors/string.js, src/selectors/tag.js, src/selectors/types.js, src/selectors/universal.js
Hey there!
We are just about to integrate this package with enzyme, a testing utility for React. you can see the PR here: https://github.com/airbnb/enzyme/pull/458
It would be useful if we could import the selector types so we cleanly parse the returned AST for our use case.
I've replaced all the string literals I found for `this.type` with constants of the same value.
=> Use and export type constants for selectors

src/__tests__/attributes.js, src/parser.js
https://github.com/postcss/postcss-selector-parser/issues/71
Maybe we should rewrite `attribute` selector parsing, inside `attribute` and `value` have trimmed value. And add `raws.spaceBeforeAttribute`, `raws.spaceAfterAttribute`, `raws.spaceBeforeOperator`, `raws.spaceAfterOperator`, `raws.spaceBeforeValue` and `raws.spaceAfterValue`. If you say yes on this i will help with this.
=> Better handling `quoted` inside attribute selector.

.gitignore, CHANGELOG.md, package-lock.json, package.json, src/parser.js
@chriseppstein This is what we talked about previously.
Summary:
dot-props is not compiled to es5, and so it breaks this library in certain environments.
(minifiers choke on it too, for example.)
The changes made it a lot more verbose than I expected though, so feel free to recommend a better approach.
=> Removed the dot-prop dependency

package-lock.json, package.json
only used during development time, so it shouldn't be installed for users of library
closes #154
=> Move `babel-eslint` to devDeps

package-lock.json, package.json
@chriseppstein, this is a dev dependency and does not impact tests.
---
If you are busy, may I publish an update as `v5.0.0-rc.3`? The publish would include these 2 fixes in since May:
- Ensure a token after a combinator https://github.com/postcss/postcss-selector-parser/commit/18ecae9ae1167ec55b6851ed468cb8b472086d80
- Allow comments after attribute insensitive flags (The case insensitive plugin would benefit from this change) https://github.com/postcss/postcss-selector-parser/commit/ccd499a1670dc24acd48fb0c79064c97dfbf33bd
=> Update PostCSS to v7

package-lock.json, package.json, src/__tests__/attributes.js
=> Update cssesc to 3.0.0

src/__tests__/id.js, src/parser.js
fixes #174
Based on: 
- https://mathiasbynens.be/notes/css-escapes (article)
- https://mathiasbynens.be/demo/html5-id (tests)
=> fix: escaping in `id` selector

src/__tests__/classes.js, src/parser.js
fixes #175 
Same fix as for previous PR (https://github.com/postcss/postcss-selector-parser/pull/178), so i added fix and tests
Based on https://mathiasbynens.be/demo/crazy-class
=> fix: class selector with `\\#`

src/__tests__/exceptions.js
fixes #152
Just ensure we don't hangs in future (avoid regressions)
=> test: throw on bad syntax instead hangs

src/__tests__/comments.js, src/parser.js
Before:
```
h2, /*test*/ h4 -> type, comment combinator type
```
After:
```
h2, /*test*/ h4 -> type, comment, type
```
=> fix: do not create invalid combinator before comment

src/__tests__/classes.js
Add some tests to understand that there is no problem in current version with escaping ':' , related to https://github.com/stylelint/stylelint/issues/3310
=> add escaped tests to classes

postcss-selector-parser.d.ts
* Add an additional parameter to Container to clarify that Root can
only contain Selectors as immediate children and Selector cannot
contain Selectors as immediate children.
* Use polymorphic `this` types for Container methods that return the
same object.
* Narrow the type for Container.walk*() to indicate that only nodes of
the given type will be passed to the callback.
* Fix the type of Container.reduce() to match the type of
Iterable.reduce().
=> Improve typescript typings

package-lock.json, package.json, src/selectors/attribute.js
Using the Node built-in `util` module can causes errors or warnings when using bundlers such as Rollup, since the module only exists in Node, not the browser. (This may require the use of something like [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins).)
We only need `util` for the `util.deprecate()` function, so we can rely on [util-deprecate](https://github.com/TooTallNate/util-deprecate) instead, which simply wraps `util.deprecate()` in Node as well as providing a browser-based equivalent.
=> fix: replace node built-in "util" module with "util-deprecate"

.travis.yml, package-lock.json, package.json, postcss-selector-parser.d.ts
This change aims to fix the following TypeScript error:
```
postcss-selector-parser.d.ts:335:15 - error TS2310: Type 'Selector' recursively references itself as a base type.
```
In addition, `npm run pretest` now checks the `.ts` file to detect such errors.
Fix #232
=> fix: TS2310 error 

src/__tests__/classes.js, src/__tests__/util/unesc.js, src/util/unesc.js
In profiling postcss I found that a significant amount of time was being
spent in [`unesc`](https://github.com/postcss/postcss-selector-parser/commits/master/src/util/unesc.js), this was due to the expensive regex checks that were
being performed on the fly for every selector in the codebase which looked to be performing quite poorly inside of modern node and v8.
----
As an experiment and based on some prior experience with this class of slowdown I migrated the implementation to one that performs a scan through the string instead of running a regex replace. By testing this on my local application I instantly saw the work from this function go from > 900 ms to ~100ms.
This implementation passes all of the existing test cases and aims to mirror the prior implementation's implementation …
=> 🚀 Rework unesc for a 63+% performance boost to all of postcss.

postcss-selector-parser.d.ts
Fix #253
I fixed the `Combinator` type by referencing `src/parser.js`. Please let me know if there are any problems.
https://github.com/postcss/postcss-selector-parser/blob/210fd21e397b03ab48b6a02090bc01d17a8749ed/src/parser.js#L500
https://github.com/postcss/postcss-selector-parser/blob/210fd21e397b03ab48b6a02090bc01d17a8749ed/src/parser.js#L552
https://github.com/postcss/postcss-selector-parser/blob/210fd21e397b03ab48b6a02090bc01d17a8749ed/src/parser.js#L587
=> fix: `Combinator.raws` property type

src/__tests__/guards.js, src/selectors/guards.js
Browsers supports also `:first-letter` and `:first-line` pseudo-elements introduced in CSS2.
- https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter
- https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line
=> fix: `isPseudoElement()` supports `:first-letter` and `:first-line`

API.md
This PR fixes the API doc for `container.atPosition(line, column)`.
I referred to the following code for the description and example:
https://github.com/postcss/postcss-selector-parser/blob/54f71ef6c3ba47c5388ab978631f148133fdfb1d/src/__tests__/container.js#L353-L375
https://github.com/postcss/postcss-selector-parser/blob/54f71ef6c3ba47c5388ab978631f148133fdfb1d/src/selectors/container.js#L128-L141
=> Fix `container.atPosition()` API doc

src/__tests__/attributes.js, src/parser.js, src/selectors/attribute.js
fixes : https://github.com/postcss/postcss-selector-parser/issues/201
These are all valid and some where not correctly parsed :
```css
[foo="a" i] {
order: 5.0;
}
[foo="b" I] {
order: 5.1;
}
[foo="c"i] {
order: 5.2;
}
[foo="d"I] {
order: 5.3;
}
[foo="e" i ] {
order: 5.4;
}
[foo="f" I ] {
order: 5.5;
}
[foo="g" i
] {
order: 5.6;
}
[foo="h" I
] {
order: 5.7;
}
```
-----
744 tests passed
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                            
-------------------|---------|----------|---------|---------|------------------------------------------------------------------------------
All files          |   95.01 |    88.32 |   96.14 |   95.46 | …
=> attribute case insensitivity

src/__tests__/namespaces.mjs, src/parser.js
fixes : https://github.com/postcss/postcss-selector-parser/issues/266
spec ref : https://drafts.csswg.org/selectors/#type-nmsp
=> throw on unexpected pipe symbols

README.md
=> Replace TravisCI badge with GitHub Actions one

postcss-selector-parser.d.ts
I think we should have `undefined` here as well, because on first/last node it should return `undefined`
=> Fix `Node#prev` and `Node#next` type for the first/last node

package.json, postcss-selector-parser.d.ts, postcss-selector-parser.test.ts, src/__tests__/container.mjs
`container.each(callback)` and `container.walk(callback)` support the second argument `index` in the `callback` function, but the argument is not reflected on the type definitions.
See the API document:
- `each`: https://github.com/postcss/postcss-selector-parser/blob/3c072b84259b1966fda4823ee7f7228cabe2a164/API.md?plain=1#L462-L463
- `walk`: https://github.com/postcss/postcss-selector-parser/blob/3c072b84259b1966fda4823ee7f7228cabe2a164/API.md?plain=1#L478-L479
Closes #249
=> fix(types): add missing `index` argument to `each`/`walk` callback

src/__tests__/node.mjs, src/__tests__/sourceIndex.mjs, src/parser.js
fixes : https://github.com/postcss/postcss-selector-parser/issues/287
=> add `sourceIndex` to `Selector` nodes

postcss-selector-parser.d.ts, src/__tests__/constructors.mjs
All of the constructor helpers always return an instance, the actual type of the returned value is always known.
=> improve typings of constructor helpers

API.md
Recent link to access intended section of the page.
=> docs: section link Error Handling

src/__tests__/comments.mjs, src/parser.js
`:is(.bar /* comment 3 */ )` would produce: `TAG COMBINATOR` inside the `:is()`.
While the ` /* comment 3 */ ` is actually just meaningless whitespace and comments.
Adding `)` to the list of tokens when checking for the end of a selector fixes this issue
=> fix erroneous trailing combinators in pseudos

src/__tests__/container.mjs, src/selectors/container.js
This change addresses some unexpected behavior when inserting nodes into a container. For example, assume you have a container containing two class nodes `.foo.baz`. While iterating that container with `each`, assume you are processing `.foo` at index 0. Today, the behavior is as follows:
- `insertBefore(.baz, .bar)` => the next callback is to `.baz` at idx 2
- `insertAfter(.foo, .bar)` => the next callback is to `.baz` at idx 2
- `prepend(.bar)` => the next callback is to `.foo` again at idx 1
With this change, the behavior is the following, respectively:
- the next callback is to `.bar` at idx 1
- the next callback is to `.bar` at idx 1
- the next callback is to `.baz` at idx 2
The newly added tests demonstrate this behavior. I've also removed the old "container#each (safe iteration)" …
=> Make insertions during iteration safe

package-lock.json, package.json
The `request `package through 2.88.2 for Node.js allow a bypass of SSRF mitigations via an attacker-controller server that does a cross-protocol redirect (HTTP to HTTPS, or HTTPS to HTTP).
The [request](https://www.npmjs.com/package/request) package is no longer supported by the maintainer. Unfortunately, it's a dependency of the `coveralls` package, which also seems abandoned. This PR helps by replacing the [coveralls](https://www.npmjs.com/package/coveralls) package with [coveralls-next](https://www.npmjs.com/package/coveralls-next).
=> Security: replace abandoned pkg coveralls with coveralls-next

src/parser.js
When determining the value of the first letter of a string, using strict equality is more efficient than startsWith. refer to [link](https://perf.link/#eyJpZCI6InpyZjd5OHg5Mm13IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS5tYXAoKCkgPT4gTWF0aC5yYW5kb20oKS50b1N0cmluZygxNikpIiwidGVzdHMiOlt7Im5hbWUiOiJGaW5kIGl0ZW0gMTAwIiwiY29kZSI6ImRhdGEuZmluZCh4ID0%2BIHguc3RhcnRzV2l0aCgnLicpKSIsInJ1bnMiOls2MDAwMCw1NTAwMCw1NzAwMCw3MjAwMCwyNzAwMCw5MzAwMCw5NjAwMCw4MTAwMCwxMTEwMDAsMzAwMCwyODAwMCwxMzAwMDAsMTUwMDAsMjEwMDAsMTU0MDAwLDEwMDAsNTYwMDAsODkwMDAsMzkwMDAsMzMwMDAsMTIwMDAsMzAwMCwyNDAwMCw0MDAwMCwxMjAwMCwxMjAwMCwzNjAwMCwxNTYwMDAsMTA3MDAwLDIwMDAwLDE3MjAwMCwzMzAwMCwyNTAwMCw3MDAwLDEzMDAwLDEyNTAwMCwxNTYwMDAsMTMwMDAsNTgwMDAsMTY5MDAwLDEyMD …
=> perf: replace startsWith with strict equality
