postcss/postcss-selector-parser

src/__tests__/sourceIndex.js, src/parser.js
This adds attribute positions, with tests mimicking the other tests I see in the sourceIndex test file.
=> Add attribute positions

src/__tests__/sourceIndex.js, src/parser.js
This one was tricker to figure out but I think I got it.
=> Add source position for pseudos

src/__tests__/sourceIndex.js, src/parser.js
Found out while testing with stylelint that the combinator positioning needed some work. This seems to take care of it.
=> Improve position for combinator

API.md
This adds some simple documentation. If you think it's adequate, I'd say this stuff is ready for release: it's working great with PostCSS to serve stylelint's purposes. Thanks for sticking with me through the work.
=> Add API doc for source and sourceIndex

src/__tests__/exceptions.js, src/__tests__/util/helpers.js, src/parser.js
=> Throw on missing opening parenthesis.

API.md, CHANGELOG.md, src/__tests__/attributes.js, src/parser.js, src/selectors/attribute.js
After this can 2.0 be released? Or is there something else blocking?
=> Rename raw to raws; closes #54

src/__tests__/parser.js, src/selectors/node.js
=> Remove hardcoded initialization spaces in node constructor.

API.md
=> Fix lossless option typo

src/__tests__/lossy.js, src/parser.js
fix(lossy): bug removing space combinator after nested token. Fixes #102.
=> Fix lossy bug using nested selectors

package-lock.json, package.json
**Changes**:
* Update `ava` and `nyc` to latest versions
* Fix `nyc` error when running `npm test` (https://github.com/istanbuljs/nyc/issues/587)
=> Update testing dependencies

src/__tests__/container.js
**Changes:**
* Add coverage for untested APIs in the `container.js`
=> Add missing unit tests to container

.gitmodules, .npmignore, .travis.yml, API.md, CHANGELOG.md, integration_test.sh, package-lock.json, package.json, postcss-selector-parser.d.ts, src/__tests__/combinators.js, src/__tests__/comments.js, src/__tests__/container.js, src/__tests__/exceptions.js, src/__tests__/lossy.js, src/__tests__/node.js, src/__tests__/sourceIndex.js, src/__tests__/stripComments.js, src/parser.js, src/selectors/container.js, src/selectors/node.js, src/tokenize.js, src/util/index.js, src/util/stripComments.js
These changes fix regressions that 4.0 introduced in stylelint.
Related: https://github.com/stylelint/stylelint/pull/3275
=> Fix stylelint and documentation

src/__tests__/attributes.js, src/parser.js
=> Fixed a parsing, in comment after attribute insensitive flag

src/__tests__/universal.js
=> test: universal selector with pseudo

src/__tests__/tags.js
=> test: tag with attribute

src/__tests__/classes.js, src/parser.js
=> Allow escaped dot within class name

src/__tests__/pseudos.js
fixes #173
Not a bug (my mistake), anyway let's add test to avoid regression in future
=> test: `:root` pseudo class

src/__tests__/classes.js
After merging we have:
```
Error: Duplicate test
```
Fix this problem
=> test: fix broken

src/__tests__/classes.js, src/util/unesc.js
=> fix: unicode surrogate pair parsing

src/__tests__/attributes.js, src/parser.js, src/selectors/attribute.js
=> fix: parsing and stringify empty attribute value

src/__tests__/nonstandard.js
Refactor + add test from prettier to avoid future regressions
=> test/refactor: non standard selector

src/__tests__/pseudos.js
From stylelint (problem was before), so i add this to avoid regression
=> test: nested pseudo classes

src/__tests__/id.js
From https://www.w3.org/TR/selectors-4/#id-selectors
=> test: id selector with universal

src/selectors/className.js, src/selectors/id.js, src/selectors/namespace.js, src/selectors/node.js
it allows easy way to implement `leadingComments` and `trailingComments` stringifying
=> refactor `toString` method in favor of polymorphism

package.json
npm pack
postcss-selector-parser-6.0.7.tgz
before: 61780
after:  42167
=> Ignore tests in published artifacts

.github/workflows/test.yml
https://github.com/nodejs/node/releases/tag/v20.19.0
Version 20.19.0 has enabled the `--experimental-detect-module` flag by default. ref https://github.com/postcss/postcss-selector-parser/pull/301#issuecomment-2644450405
=> ci: test on Node.js 24
